name: Pruebas

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar Racket
        uses: Bogdanp/setup-racket@v1.15
        with:
          version: stable
          variant: CS
          distribution: full

      - name: Ejecutar las pruebas
        run: raco test pruebas/
